### ISSUE TITLE
IDA Pro 6.95 - PyQt5

### ISSUE THREAD

**Issue by alexandreborges** [sam-b/ioctl_plugin#2]
Dear Developers, 

Good afternoon. 

This plugin uses PySides. As a suggestion, wouldn't it be better to use PyQt5 for IDA Pro 6.95?

================================================================================
win_driver_plugin.py: No module named PySide
Traceback (most recent call last):
  File "C:/Program Files/IDA 6.95/plugins/win_driver_plugin.py", line 24, in <module>
    from PySide import QtGui, QtCore
ImportError: No module named PySide
--------------------------------------------------------------------------------------

I hope you have a nice day. 

Alexandre.

**Comment by sam-b** [comment]
Good shout, will add support when I get a chance - probably end of next week.

Thanks!
Sam

**Comment by sam-b** [comment]
Gone and fixed :)

**Comment by alexandreborges** [comment]
Sam, 

 

Good morning. How are you?

 

Thank you so much. I will test it soon. 

 

I hope you have an amazing day.



Alexandre. 

 

De: Sam Brown [mailto:notifications@github.com] 
Enviada em: segunda-feira, 5 de junho de 2017 13:50
Para: mwrlabs/win_driver_plugin
Cc: Alexandre Borges; Author
Assunto: Re: [mwrlabs/win_driver_plugin] IDA Pro 6.95 - PyQt5 (#2)

 

Gone and fixed :)
